/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as i1NchRouterSol from "./I1nchRouter.sol";
export type { i1NchRouterSol };
export type { ICreate3Deployer } from "./ICreate3Deployer";
export type { IDaiLikePermit } from "./IDaiLikePermit";
export type { IERC20MetadataUppercase } from "./IERC20MetadataUppercase";
export type { IPermit2 } from "./IPermit2";
export type { IWETH } from "./IWETH";
