/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20MetadataUppercase,
  IERC20MetadataUppercaseInterface,
} from "../../../contracts/interfaces/IERC20MetadataUppercase";

const _abi = [
  {
    inputs: [],
    name: "NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SYMBOL",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC20MetadataUppercase__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20MetadataUppercaseInterface {
    return new Interface(_abi) as IERC20MetadataUppercaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20MetadataUppercase {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC20MetadataUppercase;
  }
}
