/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFinalizeVerifier,
  IFinalizeVerifierInterface,
} from "../../../contracts/IVerifier.sol/IFinalizeVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[3]",
        name: "_publicInputs",
        type: "uint256[3]",
      },
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFinalizeVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IFinalizeVerifierInterface {
    return new Interface(_abi) as IFinalizeVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFinalizeVerifier {
    return new Contract(address, _abi, runner) as unknown as IFinalizeVerifier;
  }
}
