/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISwapVerifier,
  ISwapVerifierInterface,
} from "../../../contracts/IVerifier.sol/ISwapVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[4]",
        name: "_publicInputs",
        type: "uint256[4]",
      },
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISwapVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapVerifierInterface {
    return new Interface(_abi) as ISwapVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISwapVerifier {
    return new Contract(address, _abi, runner) as unknown as ISwapVerifier;
  }
}
