/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAggregationExecutor,
  IAggregationExecutorInterface,
} from "../../../../contracts/interfaces/I1nchRouter.sol/IAggregationExecutor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "msgSender",
        type: "address",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IAggregationExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IAggregationExecutorInterface {
    return new Interface(_abi) as IAggregationExecutorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAggregationExecutor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAggregationExecutor;
  }
}
