/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRelayerInterface extends Interface {
  getFunction(
    nameOrSignature: "TOKEN_A" | "TOKEN_B" | "deposit" | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "TOKEN_A", values?: undefined): string;
  encodeFunctionData(functionFragment: "TOKEN_B", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "TOKEN_A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TOKEN_B", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface IRelayer extends BaseContract {
  connect(runner?: ContractRunner | null): IRelayer;
  waitForDeployment(): Promise<this>;

  interface: IRelayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TOKEN_A: TypedContractMethod<[], [string], "nonpayable">;

  TOKEN_B: TypedContractMethod<[], [string], "nonpayable">;

  deposit: TypedContractMethod<
    [
      _cNode: BytesLike,
      _cModel: BytesLike,
      _balanceA: BigNumberish,
      _balanceB: BigNumberish,
      _proof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [
      _nullifier: BytesLike,
      _balanceA: BigNumberish,
      _balanceB: BigNumberish,
      _vault: AddressLike,
      _proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TOKEN_A"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "TOKEN_B"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      _cNode: BytesLike,
      _cModel: BytesLike,
      _balanceA: BigNumberish,
      _balanceB: BigNumberish,
      _proof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      _nullifier: BytesLike,
      _balanceA: BigNumberish,
      _balanceB: BigNumberish,
      _vault: AddressLike,
      _proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
